
test: 
	../../src/txt2bin test.txt test.bin
	../../src/dasmx86 test.dx86
	../../src/txt2bin test8086.txt test8086.bin
	../../src/dasmx86 test8086.dx86
	../../src/txt2bin test286.txt test286.bin
	../../src/dasmx86 test286.dx86
	../../src/txt2bin test386.txt test386.bin
	../../src/dasmx86 test386.dx86

clean:
	rm -f test.bin test8086.bin test286.bin test386.bin
