name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make all dasms
      run: |
        cd src
        make
    - name: Run all tests
      run: |
        cd test
        for f in *; do pushd $f; make; popd; done
